# config.yaml
data:
  train_data: data/train_data.txt
  valid_data: data/valid_data.txt
  vocab_file: data/vocab.txt
  max_length: 128

model:
  embedding_size: 128
  hidden_size: 256
  num_layers: 2
  num_blocks: 3
  dropout: 0.1
  bidirectional: false
  lstm_type: slstm

training:
  batch_size: 32
  num_epochs: 10
  learning_rate: 0.001

device: mps
seed: 42